import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import axios from 'axios'
import {useState} from 'react'
import {BsSearch} from 'react-icons/bs';
import Weather from '../components/weather'

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [city, setCity] = useState('')
  const [weater, setWeather] = useState({});
  const [loading, setLoading] = useState(false);


  const fetchWeather = (e) => {
    e.preventDefault();
    setLoading(true);
    
    const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=77fcc8ce22ab9dede2f8ce43331f6dcf`
    axios.get(url).then((response) => {
      setWeather(response.data)
      console.log(response.data)
    })
    setCity('');
    setLoading(false);
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div>
        {/* <form onSubmit={fetchWeather} className='zipCodeForm'>
            <div>
                <input onChange={(e) => setZipCode(e.target.value)}
                    className='zipCodeForm'
                    type = 'text'
                    placeholder='Type zipcode'
                />
            </div>
        </form> */}
        <form onSubmit={fetchWeather} className='cityForm'>
            <div>
                <input onChange={(e) => setCity(e.target.value)}
                    className='cityForm'
                    type = 'text'
                    placeholder='Search city'
                />
            </div>
        </form>
        <button onClick={fetchWeather}>Fetch data 
                <BsSearch size={20}/>
        </button>
        {Weather.main && <Weather data={weather}/>}
      </div>
    </>
  );
}
